### PR TITLE
relaton/relaton#110 add deploy workflow

### PR DESCRIPTION
**Pull request by CAMOBAP**
- relaton/relaton#110

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@andrew2net @ronaldtse can you confirm that GitHub Pages is enabled for this repository

**Comment by ronaldtse** [comment]
@camobap I've enabled GH Pages.

**Comment by ronaldtse** [comment]
@CAMOBAP but do we want to deploy PR branches?

**Comment by CAMOBAP** [comment]
> @CAMOBAP but do we want to deploy PR branches?

nope, we are not, for PRs CI just build an site but do not deploy it

**Comment by ronaldtse** [comment]
The build is now failing, let's merge when it's fixed. Thanks.

**Review by andrew2net — APPROVED** [review]

**Comment by andrew2net** [comment]
@CAMOBAP Some indexes have IDs as parts. For example, the `index1.yaml` contains:
```yaml
---
- :id:
    :code: '01'
  :file: data/01.yaml
- :id:
    :code: WCA-terms
    :suff: '01'
  :file: data/wca-terms_01.yaml
- :id:
    :code: xfa-formcalc
    :date: '19990614'
  :file: data/xfa-formcalc-19990614.yaml
- :id:
    :code: xfa-template
    :date: '19990614'
  :file: data/xfa-template-19990614.yaml
- :id:
    :code: 07-WebData
  :file: data/07-webdata.yaml
- :id:
    :code: css3-namespace
    :stage: WD
    :date: '19990625'
  :file: data/wd-css3-namespace-19990625.yaml
- :id:
    :code: CCPPexchange
    :type: NOTE
    :date: '19990624'
  :file: data/note-ccppexchange-19990624.yaml
  ...
```
As you can see the IDs are Hash, not string. In additional, the IDs may have different attributes. So we need to add a repository-specific setting that describes rules to make reference form ID.
I think we can add setting like:
```yaml
jekyll-index:
  reference:
    - part: :type
    - delimiter: '-'
    - part: :code
    - delimiter: '-'
    - part: :date
```
To render such references we need to update the `_plugins/jekyll-index.rb`:
```ruby
    def reference(item, hash)
      ref = create_ref item[:id]
      if @site.config['jekyll-index']['add_type_to_reference']
        type = hash['docid'].find { |id| id['primary'] }['type']
        return "#{ref} #{item[:id]}"
      end

      ref
    end

    def create_ref(id)
      return id if id.is_a? String

      ...
    end
```
Could you implement this?

**Comment by CAMOBAP** [comment]
@andrew2net I think so, Just to be on the same page, maybe it's possible to "detect" this automatically in `_plugins/jekyll-index.rb` without extra configuration i.e.:

1. If `id` is a string user it as string
2. if `id` is a `Hash` take each property and concat values with `-` delimiter, will it works?

**Comment by andrew2net** [comment]
> @andrew2net I think so, Just to be on the same page, maybe it's possible to "detect" this automatically in `_plugins/jekyll-index.rb` without extra configuration i.e.:

@CAMOBAP No, it won't work without the extra configuration. We have different delimiters in other repos. Also, different delimiters are used between IDs' parts. In addition, an ID parts order in indexes may not match to references.

> 
> 1. If `id` is a string user it as string

Correct.

> 2. if `id` is a `Hash` take each property and concat values with `-` delimiter, will it works?

No, as I said it can be different even in one reference.

**Comment by CAMOBAP** [comment]
thanks for clarification, https://github.com/relaton/jekyll-theme-relaton-data-index/issues/2 - reported

**Comment by ronaldtse** [comment]
@andrew2net @CAMOBAP for ID parsing and storage, why don't we just use the pubid gems? It's exactly why we need them.

**Comment by CAMOBAP** [comment]
> @andrew2net @CAMOBAP for ID parsing and storage, why don't we just use the pubid gems? It's exactly why we need them. 

Thanks a lot for suggesting, looks reasonable for me

**Comment by andrew2net** [comment]
> @andrew2net @CAMOBAP for ID parsing and storage, why don't we just use the pubid gems? It's exactly why we need them.

@CAMOBAP we don't have implemented and integrated pubids for all Relaton flavors yet.

**Pull request merged**
